name: Benchmark

on:
    workflow_dispatch:
    pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        language:
          - "crystal"
          - "go"
          - "nodejs"
          - "php"
          - "python"
          - "ruby"
    env:
      ISHOCON_APP_LANG: ${{ matrix.language }}
    steps:
      - uses: actions/checkout@v2
      - run: make change-lang LANG=$ISHOCON_APP_LANG
      - run: make build up bench-with-db-restart
        timeout-minutes: 15
