name: Benchmark

on:
    workflow_dispatch:
    push:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        language:
          - "crystal"
          - "go"
          - "nodejs"
          - "php"
          - "python"
          - "ruby"
    env:
      ISHOCON_APP_LANG: ${{ matrix.language }}
      UNAME: ${{ github.actor }}
    steps:
      - uses: actions/checkout@v4
      - run: make change-lang LANG=$ISHOCON_APP_LANG
      - run: |
          sed -i 's/ishocon2-app-base/'"${{ env.UNAME }}"'\/ishocon2-app-base/g' ./docker-compose.yml;
          sed -i 's/ishocon2-bench/'"${{ env.UNAME }}"'\/ishocon2-app-bench/g' ./docker-compose.yml;
          cat ./docker-compose.yml;
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./docker/app/base/Dockerfile
          cache-from: type=gha
          cache-to: type=local,mode=max,dest=.cache/base
          load: true
          tags: ${{ env.UNAME }}/ishocon2-app-base:latest
      - uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./docker/benchmarker/Dockerfile
          cache-from: type=gha
          cache-to: type=local,mode=max,dest=.cache/bench
          load: true
          tags: ${{ env.UNAME }}/ishocon2-app-bench:latest
      - uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./docker/app/${{ env.ISHOCON_APP_LANG }}/Dockerfile
          cache-from: type=local,src=.cache/base
          cache-to: type=gha,mode=max
          load: true
          tags: ${{ env.UNAME }}/ishocon2-app-${{ env.ISHOCON_APP_LANG }}:latest
      - run: make build
        timeout-minutes: 5
      - run: make up bench-with-db-init
        timeout-minutes: 10
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
