name: Benchmark

on:
    workflow_dispatch:
    push:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        language:
          - "crystal"
          - "go"
          - "nodejs"
          - "php"
          - "python"
          - "ruby"
    env:
      ISHOCON_APP_LANG: ${{ matrix.language }}
    steps:
      - uses: actions/checkout@v4
      - run: make change-lang LANG=$ISHOCON_APP_LANG
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./docker/app/${{ env.ISHOCON_APP_LANG }}/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ github.actor }}/ishocon2-app-${{ env.ISHOCON_APP_LANG }}:latest
      - run: make build
        timeout-minutes: 5
      - run: make up bench-with-db-init
        timeout-minutes: 10
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
