name: Benchmark

on:
    workflow_dispatch:
    push:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        language:
          - "crystal"
          - "go"
          - "nodejs"
          - "php"
          - "python"
          - "ruby"
    env:
      ISHOCON_APP_LANG: ${{ matrix.language }}
      UNAME: ${{ github.actor }}
    steps:
      - uses: actions/checkout@v4
      - run: make change-lang LANG=$ISHOCON_APP_LANG
      - run: |
          sed -i 's/ishocon2-app-base/${{ env.UNAME }}\/ishocon2-app-base/g' ./docker-compose.yml
          cat ./docker-compose.yml
      - run: make build
        timeout-minutes: 5
      - run: make up bench-with-db-init
        timeout-minutes: 10
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
