name: Build and push images

on:
    workflow_dispatch:
    push:
      branches:
        - master

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-and-push-base-and-bench-images:
    name: Build and push base and bench images
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      UNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.UNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: make pull
      - name: Build and push bench image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./docker/benchmarker/Dockerfile
          tags: ${{ env.UNAME }}/ishocon2-bench:latest,${{ env.UNAME }}/ishocon2-bench:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64/v8
      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./docker/app/base/Dockerfile
          tags: ${{ env.UNAME }}/ishocon2-app-base:latest,${{ env.UNAME }}/ishocon2-app-base:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64/v8
  build-app-images:
    name: Build app images
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: build-and-push-base-and-bench-images
    strategy:
      fail-fast: false
      matrix:
        language:
          - "crystal"
          - "go"
          - "nodejs"
          - "php"
          - "python"
          - "ruby"
    env:
      ISHOCON_APP_LANG: ${{ matrix.language }}
      UNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.UNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: make pull
      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./docker/app/base/Dockerfile
          tags: ${{ env.UNAME }}/ishocon2-app-${{ env.ISHOCON_APP_LANG }}:latest,${{ env.UNAME }}/ishocon2-app-${{ github.sha }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64/v8
