name: Build and push images

on:
    workflow_dispatch:
    push:
      branches:
        - master

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        language:
          - "crystal"
          - "go"
          - "nodejs"
          - "php"
          - "python"
          - "ruby"
    env:
      ISHOCON_APP_LANG: ${{ matrix.language }}
      UNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Replace base image in docker-compose.yml with github actor name
        run: |
          make change-lang
          sed -i 's/ishocon2-app-base/${{ env.UNAME }}\/ishocon2-app-base/g' ./docker-compose.yml
          cat ./docker-compose.yml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.UNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push bench image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./docker/benchmarker/Dockerfile
          tags: ${{ env.UNAME }}/ishocon2-app-bench:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./docker/app/base/Dockerfile
          tags: ${{ env.UNAME }}/ishocon2-app-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./docker/app/base/Dockerfile
          tags: ${{ env.UNAME }}/ishocon2-app-${{ env.ISHOCON_APP_LANG }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
