name: Build and push images

on:
    workflow_dispatch:
    push:
      branches:
        - master
        - feat/apple-silicon

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-and-push-images:
    name: Build and push images
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        language:
          - "crystal"
          - "go"
          - "nodejs"
          - "php"
          - "python"
          - "ruby"
        arch:
          - "arm64v8"
          - "armv7l"
          - "ppc64le"
          - "s390x"
          - "x86_64"
    env:
      ISHOCON_APP_LANG: ${{ matrix.language }}
      UNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.UNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build images
        run: make build
      - name: Push images
        run: make push
